version: '3.3'
services:
  php:
    container_name: php
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./storage:/var/www/storage
    env_file: '.env.prod'
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./storage/logs/:/var/log/nginx
    ports:
      - 8080:80
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'quest'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: